k3s:
  max-container-num: 10

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/os?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver


disk:
  path: "data/disk"

logging:
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} %c %M %L %m%n"
  file:
    name: springboot.log
    path: ./

