apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - name: busy
      image: busybox
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: ngx-conf
  volumes:
    - name: ngx-conf
      emptyDir: {}
