apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
# local storage /home/jking/IdeaProjects/backend/data/nfs-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  hostPath:
    path: "/home/jking/IdeaProjects/backend/data/nfs-data"