apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-provisioning-demo
spec:
    accessModes:
        - ReadWriteMany
    resources:
      requests:
          storage: 1Gi
    storageClassName: local-storage
