apiVersion: v1
kind: Pod
metadata:
  name: uos
  labels:
      app: uos
spec:
  containers:
    - name: uos
      image: uos:v0.2.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 6080
      env:
        - name: VNC_PW
          value: "12345678"


